// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZvnLrZc52VzUVd9HutWVF-rTUtL3_oJY',
    appId: '1:283492405556:web:9b4f4e4622bd3c91545561',
    messagingSenderId: '283492405556',
    projectId: 'expenseapp-cb4f5',
    authDomain: 'expenseapp-cb4f5.firebaseapp.com',
    storageBucket: 'expenseapp-cb4f5.firebasestorage.app',
    measurementId: 'G-78M4K6F04J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKrVIK5yD_cgqSj7LovsXHsFqQ5wCwhfQ',
    appId: '1:283492405556:android:296c9aa9f024f49e545561',
    messagingSenderId: '283492405556',
    projectId: 'expenseapp-cb4f5',
    storageBucket: 'expenseapp-cb4f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1rge_GF-eq79KtjVCS9Ns5pbj_8lcuGk',
    appId: '1:283492405556:ios:59f81aec87399c0b545561',
    messagingSenderId: '283492405556',
    projectId: 'expenseapp-cb4f5',
    storageBucket: 'expenseapp-cb4f5.firebasestorage.app',
    iosBundleId: 'com.antigravity.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1rge_GF-eq79KtjVCS9Ns5pbj_8lcuGk',
    appId: '1:283492405556:ios:59f81aec87399c0b545561',
    messagingSenderId: '283492405556',
    projectId: 'expenseapp-cb4f5',
    storageBucket: 'expenseapp-cb4f5.firebasestorage.app',
    iosBundleId: 'com.antigravity.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZvnLrZc52VzUVd9HutWVF-rTUtL3_oJY',
    appId: '1:283492405556:web:b9a76a91ef054323545561',
    messagingSenderId: '283492405556',
    projectId: 'expenseapp-cb4f5',
    authDomain: 'expenseapp-cb4f5.firebaseapp.com',
    storageBucket: 'expenseapp-cb4f5.firebasestorage.app',
    measurementId: 'G-CWH0TWNBQP',
  );
}
